const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTCHMENT = "NEW_ATTCHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

export { ALERT, REFETCH_CHATS, NEW_ATTCHMENT, NEW_MESSAGE_ALERT };
